
namespace SharedResources
{
    public class NewLead
    {
        public string CampaignId { get; set; }
        public string AgentId { get; set; }
        public string ExternalId { get; set; }
        public string RefId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string SSN { get; set; }
        public string MaritalStatus { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string DateofBirth { get; set; }
        public string BaseIncome { get; set; }
        public string OccupationalStatus { get; set; }
        public string EmployerName { get; set; }
        public string FirstName_Coborrower { get; set; }
        public string LastName_Coborrower { get; set; }
        public string SSN_Coborrower { get; set; }
        public string State_Coborrower { get; set; }
        public string ZipCode_Coborrower { get; set; }
        public string DateofBirth_Coborrower { get; set; }
        public string BaseIncome_Coborrower { get; set; }
        public string DayPhone { get; set; }
        public string EveningPhone { get; set; }
        public string CreditProfile { get; set; }
        public string LoanPurpose { get; set; }
        public string ExistingHomeValue { get; set; }
        public string PropertyFound { get; set; }
        public string IntendedPropertyUse { get; set; }
        public string PropertyAddress { get; set; }
        public string PropertyCity { get; set; }
        public string PropertyState { get; set; }
        public string PropertyZipCode { get; set; }
        public string PropertyCounty { get; set; }
        public string PropertyType { get; set; }
        public string AmortizationType { get; set; }
        public string CurrentNeedSituation { get; set; }
        public string PurposeofRefinance { get; set; }
        public string LoanType { get; set; }
        public string LMBPreferredLoanType { get; set; }
        public string LoanTerm_Years { get; set; }
        public string DownPaymentAmount { get; set; }
        public string Bankruptcyinlast7years { get; set; }
        public string ClientIPAddress { get; set; }
        public string Ownedpropertyinlast3years { get; set; }
        public string NeedPurchaseRealtor { get; set; }
        public string RealEstateAgentName { get; set; }
        public string RealEstateAgentPhone { get; set; }
        public string NeedSellingRealtor { get; set; }
        public string AdditionalInformation { get; set; }
        public string MobilePhone { get; set; }
        public string EmploymentPosition { get; set; }
        public string EmploymentLengthInYears { get; set; }
        public string CreditScore { get; set; }
        public string Email_Coborrower { get; set; }
        public string DayPhone_Coborrower { get; set; }
        public string EveningPhone_Coborrower { get; set; }
        public string MobilePhone_Coborrower { get; set; }
        public string MaritalStatus_Coborrower { get; set; }
        public string OccupationalStatus_Coborrower { get; set; }
        public string EmployerName_Coborrower { get; set; }
        public string EmployerPosition_Coborrower { get; set; }
        public string EmploymentLengthInYears_Coborrower { get; set; }
        public string CreditProfile_Coborrower { get; set; }
        public string CreditScore_Coborrower { get; set; }
        public string ViewinGoogleMaps { get; set; }
        public string ViewZillowdetails { get; set; }
        public string YearBuilt { get; set; }
        public string GrossRent { get; set; }
        public string OccupancyRate_Percent { get; set; }
        public string County { get; set; }
        public string YearsinProperty { get; set; }
        public string Address_Coborrower { get; set; }
        public string City_Coborrower { get; set; }
        public string County_Coborrower { get; set; }
        public string YearsinProperty_Coborrower { get; set; }
        public string _1stLoanAmount { get; set; }
        public string FirstRateType { get; set; }
        public string FirstRate_Percent { get; set; }
        public string _2ndLoanAmount { get; set; }
        public string SecondRateType { get; set; }
        public string SecondRate_Percent { get; set; }
        public string LienPosition { get; set; }
        public string LoanAmount { get; set; }
        public string PurchasePrice { get; set; }
        public string DownPayment_Percent { get; set; }
        public string MIPFundingFee { get; set; }
        public string Rate_Percent { get; set; }
        public string SubordinateFinancingAmount { get; set; }
        public string LoanToValue_LTV { get; set; }
        public string CombinedLTV_CLTV { get; set; }
        public string YearAcquired { get; set; }
        public string OriginalCost { get; set; }
        public string AmountExistingLiens { get; set; }
        public string TotalHouseholdIncome { get; set; }
        public string TotalHousingExpense { get; set; }
        public string Top { get; set; }
        public string OtherIncome { get; set; }
        public string TotalMonthlyIncome { get; set; }
        public string OtherIncome_Coborrower { get; set; }
        public string TotalMonthlyIncome_Coborrower { get; set; }
        public string MonthlyMortgagePayment { get; set; }
        public string MonthlyPaymentfromCalculator { get; set; }
        public string OtherMonthlyHousingExpense { get; set; }
        public string TotalProposedHousingExpense { get; set; }
        public string MonthlyNon_MortgageDebtPayments { get; set; }
        public string LiquidAssets { get; set; }
        public string Investments { get; set; }
        public string PersonalProperty { get; set; }
        public string RealProperty { get; set; }
        public string CurrentLiabilities { get; set; }
        public string LongTermLiabilities { get; set; }
        public string NetWorth { get; set; }
        public string LoanAmount_forthistabonly { get; set; }
        public string InterestRate_Percent { get; set; }
        public string Term_Years { get; set; }
        public string NumberofPaymentsPerYear { get; set; }
        public string MonthlyPaymentAmount { get; set; }
        public string ScheduledNumberofPayments { get; set; }
        public string CumulativeFinanceCharge { get; set; }
        public string CumulativePaymentValue { get; set; }
        public string TotalSettlementCharges { get; set; }
        public string NetLockPrice { get; set; }
        public string TotalLoanRevenue { get; set; }
        public string OriginationCommission { get; set; }
        public string WarehouseCosts { get; set; }
        public string OtherDirectCosts { get; set; }
        public string AllocatedCosts { get; set; }
        public string NetGain_LossforBanker { get; set; }
        public string FirstpaymentDate { get; set; }
        public string LockExpiryDate { get; set; }
        public string FundedDate { get; set; }
        public string LeadProviderName { get; set; }
        public string LeadPricePaid_USD { get; set; }
        public string InvalidPhoneNumber { get; set; }
        public string FalseInformation { get; set; }
        public string Duplicate_ManuallyDetermined { get; set; }
        public string OutofFilter { get; set; }
        public string NotSpecifiedPerson { get; set; }
        public string FalselyIncented { get; set; }
        public string DownPaymentAmount_ { get; set; }
        public string DownPaymentPercent { get; set; }
        public string MaxLoanAmountDesired { get; set; }
        public string ReferralName { get; set; }
        public string MiddleName { get; set; }
        public string MiddleName_Coborrower { get; set; }
        public string TotalAssets { get; set; }
        public string TotalLiabilities { get; set; }
        public string InterestRateperPeriod_Percent { get; set; }
        public string TotalLoanCosts { get; set; }
        public string Bottom { get; set; }
        public string Top_Bottom { get; set; }
        public string ZillowUrl { get; set; }
        public string RealEstateCompanyName { get; set; }
        public string ReferringPersonsEmail { get; set; }
        public string GetZillowURL { get; set; }
        public string FirstName_FromSummary { get; set; }
        public string LastName_FromSummary { get; set; }
        public string DayPhone_FromSummary { get; set; }
        public string EveningPhone_FromSummary { get; set; }
        public string MobilePhone_FromSummary { get; set; }
        public string PropertyState_FromSummary { get; set; }
        public string PurchasePrice_FromSummary { get; set; }
        public string LoanAmount_FromSummary { get; set; }
        public string Email_FromSummary { get; set; }
        public string CreditProfile_FromSummary { get; set; }
        public string PropertyType_FromSummary { get; set; }
        public string PropertyAddress_FromSummary { get; set; }
        public string PropertyCity_FromSummary { get; set; }
        public string PropertyZipCode_FromSummary { get; set; }
        public string SpouseFirstName { get; set; }
        public string SpouseLastName { get; set; }
        public string FirstTimeHomeBuyer { get; set; }
        public string NewHomeValue { get; set; }
        public string MortgageBalance_1st { get; set; }
        public string InterestRate_1st { get; set; }
        public string RateType_1st { get; set; }
        public string MortgageBalance_2nd { get; set; }
        public string InterestRate_2nd { get; set; }
        public string DesiredLoanAmount { get; set; }
        public string EstimatedDownPayment { get; set; }
        public string LTV { get; set; }
        public string EligibleforVALoan { get; set; }
        public string VALoanFirstTimeUse { get; set; }
        public string HasVARelatedDisability { get; set; }
        public string VeteranType { get; set; }
        public string CoborrowerEligibleforVALoan { get; set; }
        public string CoborrowerVALoanFirstTimeUse { get; set; }
        public string CoborrowerHasVARelatedDisability { get; set; }
        public string CoborrowerVeteranType { get; set; }
        public string LoanOriginationYear { get; set; }
        public string NYLXLoanID { get; set; }
        public string ZillowContactPrice { get; set; }
        public string _1stProductName { get; set; }
        public string _1stInterestRate { get; set; }
        public string _1stAssumedLockDays { get; set; }
        public string _1stAmortizationType { get; set; }
        public string _1stInitialCap { get; set; }
        public string _1stIntroPeriod { get; set; }
        public string _1stARMIndexType { get; set; }
        public string _1stDueInPeriods { get; set; }
        public string _1stInterestOnlyLoan { get; set; }
        public string _1stInterestOnlyPeriod { get; set; }
        public string _1stIsJumbo { get; set; }
        public string _1stLifetimeCap { get; set; }
        public string _1stMargin { get; set; }
        public string _1stNotDueinMonths { get; set; }
        public string _1stOfferID { get; set; }
        public string _1stOfferType { get; set; }
        public string _1stPoints { get; set; }
        public string _1stPrepayPenalty { get; set; }
        public string _1stPricingTypeId { get; set; }
        public string _1stTerminMonths { get; set; }
        public string _1stRateAdjustmentCap { get; set; }
        public string _1stRateAdjustmentPeriod { get; set; }
        public string _1stAPR { get; set; }
        public string _1stFHAAnnualInsurancePremium { get; set; }
        public string _1stFHAUpfrontInsurancePremium { get; set; }
        public string _1stAnnualMIPPercent { get; set; }
        public string _1stVALoanFundingFeePercent { get; set; }
        public string _2ndProductName { get; set; }
        public string _2ndInterestRate { get; set; }
        public string _2ndAssumedLockDays { get; set; }
        public string _2ndAmortizationType { get; set; }
        public string _2ndInitialCap { get; set; }
        public string _2ndIntroPeriod { get; set; }
        public string _2ndARMIndexType { get; set; }
        public string _2ndDueInPeriods { get; set; }
        public string _2ndInterestOnlyLoan { get; set; }
        public string _2ndInterestOnlyPeriod { get; set; }
        public string _2ndIsJumbo { get; set; }
        public string _2ndLifetimeCap { get; set; }
        public string _2ndMargin { get; set; }
        public string _2ndNotDueinMonths { get; set; }
        public string _2ndOfferID { get; set; }
        public string _2ndOfferType { get; set; }
        public string _2ndPoints { get; set; }
        public string _2ndPrepayPenalty { get; set; }
        public string _2ndPricingTypeId { get; set; }
        public string _2ndTerminMonths { get; set; }
        public string _2ndRateAdjustmentCap { get; set; }
        public string _2ndRateAdjustmentPeriod { get; set; }
        public string _2ndAPR { get; set; }
        public string _2ndFHAAnnualInsurancePremium { get; set; }
        public string _2ndFHAUpfrontInsurancePremium { get; set; }
        public string _2ndAnnualMIPPercent { get; set; }
        public string _2ndVALoanFundingFeePercent { get; set; }
        public string _3rdProductName { get; set; }
        public string _3rdInterestRate { get; set; }
        public string _3rdAssumedLockDays { get; set; }
        public string _3rdAmortizationType { get; set; }
        public string _3rdInitialCap { get; set; }
        public string _3rdIntroPeriod { get; set; }
        public string _3rdARMIndexType { get; set; }
        public string _3rdDueInPeriods { get; set; }
        public string _3rdInterestOnlyLoan { get; set; }
        public string _3rdInterestOnlyPeriod { get; set; }
        public string _3rdIsJumbo { get; set; }
        public string _3rdLoanAmount { get; set; }
        public string _3rdLifetimeCap { get; set; }
        public string _3rdMargin { get; set; }
        public string _3rdNotDueinMonths { get; set; }
        public string _3rdOfferID { get; set; }
        public string _3rdOfferType { get; set; }
        public string _3rdPoints { get; set; }
        public string _3rdPrepayPenalty { get; set; }
        public string _3rdPricingTypeId { get; set; }
        public string _3rdTerminMonths { get; set; }
        public string _3rdRateAdjustmentCap { get; set; }
        public string _3rdRateAdjustmentPeriod { get; set; }
        public string _3rdAPR { get; set; }
        public string _3rdFHAAnnualInsurancePremium { get; set; }
        public string _3rdFHAUpfrontInsurancePremium { get; set; }
        public string _3rdAnnualMIPPercent { get; set; }
        public string _3rdVALoanFundingFeePercent { get; set; }
        public string _1stOffer_1stFeeCode { get; set; }
        public string _1stOffer_1stFeeAmount { get; set; }
        public string _1stOffer_1stFeeDescription { get; set; }
        public string _1stOffer_2ndFeeCode { get; set; }
        public string _1stOffer_2ndFeeAmount { get; set; }
        public string _1stOffer_2ndFeeDescription { get; set; }
        public string _1stOffer_3rdFeeCode { get; set; }
        public string _1stOffer_3rdFeeAmount { get; set; }
        public string _1stOffer_3rdFeeDescription { get; set; }
        public string _1stOffer_4thFeeCode { get; set; }
        public string _1stOffer_4thFeeAmount { get; set; }
        public string _1stOffer_4thFeeDescription { get; set; }
        public string _1stOffer_5thFeeCode { get; set; }
        public string _1stOffer_5thFeeAmount { get; set; }
        public string _1stOffer_5thFeeDescription { get; set; }
        public string _1stOffer_6thFeeCode { get; set; }
        public string _1stOffer_6thFeeAmount { get; set; }
        public string _1stOffer_6thFeeDescription { get; set; }
        public string _1stOffer_7thFeeCode { get; set; }
        public string _1stOffer_7thFeeAmount { get; set; }
        public string _1stOffer_7thFeeDescription { get; set; }
        public string _1stOffer_8thFeeCode { get; set; }
        public string _1stOffer_8thFeeAmount { get; set; }
        public string _1stOffer_8thFeeDescription { get; set; }
        public string _1stOffer_9thFeeCode { get; set; }
        public string _1stOffer_9thFeeAmount { get; set; }
        public string _1stOffer_9thFeeDescription { get; set; }
        public string _1stOffer_10thFeeCode { get; set; }
        public string _1stOffer_10thFeeAmount { get; set; }
        public string _1stOffer_10thFeeDescription { get; set; }
        public string _1stOffer_11thFeeCode { get; set; }
        public string _1stOffer_11thFeeAmount { get; set; }
        public string _1stOffer_11thFeeDescription { get; set; }
        public string _1stOffer_12thFeeCode { get; set; }
        public string _1stOffer_12thFeeAmount { get; set; }
        public string _1stOffer_12thFeeDescription { get; set; }
        public string _2ndOffer_1stFeeCode { get; set; }
        public string _2ndOffer_1stFeeAmount { get; set; }
        public string _2ndOffer_1stFeeDescription { get; set; }
        public string _2ndOffer_2ndFeeCode { get; set; }
        public string _2ndOffer_2ndFeeAmount { get; set; }
        public string _2ndOffer_2ndFeeDescription { get; set; }
        public string _2ndOffer_3rdFeeCode { get; set; }
        public string _2ndOffer_3rdFeeAmount { get; set; }
        public string _2ndOffer_3rdFeeDescription { get; set; }
        public string _2ndOffer_4thFeeCode { get; set; }
        public string _2ndOffer_4thFeeAmount { get; set; }
        public string _2ndOffer_4thFeeDescription { get; set; }
        public string _2ndOffer_5thFeeCode { get; set; }
        public string _2ndOffer_5thFeeAmount { get; set; }
        public string _2ndOffer_5thFeeDescription { get; set; }
        public string _2ndOffer_6thFeeCode { get; set; }
        public string _2ndOffer_6thFeeAmount { get; set; }
        public string _2ndOffer_6thFeeDescription { get; set; }
        public string _2ndOffer_7thFeeCode { get; set; }
        public string _2ndOffer_7thFeeAmount { get; set; }
        public string _2ndOffer_7thFeeDescription { get; set; }
        public string _2ndOffer_8thFeeCode { get; set; }
        public string _2ndOffer_8thFeeAmount { get; set; }
        public string _2ndOffer_8thFeeDescription { get; set; }
        public string _2ndOffer_9thFeeCode { get; set; }
        public string _2ndOffer_9thFeeAmount { get; set; }
        public string _2ndOffer_9thFeeDescription { get; set; }
        public string _2ndOffer_10thFeeCode { get; set; }
        public string _2ndOffer_10thFeeAmount { get; set; }
        public string _2ndOffer_10thFeeDescription { get; set; }
        public string _2ndOffer_11thFeeCode { get; set; }
        public string _2ndOffer_11thFeeAmount { get; set; }
        public string _2ndOffer_11thFeeDescription { get; set; }
        public string _2ndOffer_12thFeeCode { get; set; }
        public string _2ndOffer_12thFeeAmount { get; set; }
        public string _2ndOffer_12thFeeDescription { get; set; }
        public string _3rdOffer_1stFeeCode { get; set; }
        public string _3rdOffer_1stFeeAmount { get; set; }
        public string _3rdOffer_1stFeeDescription { get; set; }
        public string _3rdOffer_2ndFeeCode { get; set; }
        public string _3rdOffer_2ndFeeAmount { get; set; }
        public string _3rdOffer_2ndFeeDescription { get; set; }
        public string _3rdOffer_3rdFeeCode { get; set; }
        public string _3rdOffer_3rdFeeAmount { get; set; }
        public string _3rdOffer_3rdFeeDescription { get; set; }
        public string _3rdOffer_4thFeeCode { get; set; }
        public string _3rdOffer_4thFeeAmount { get; set; }
        public string _3rdOffer_4thFeeDescription { get; set; }
        public string _3rdOffer_5thFeeCode { get; set; }
        public string _3rdOffer_5thFeeAmount { get; set; }
        public string _3rdOffer_5thFeeDescription { get; set; }
        public string _3rdOffer_6thFeeCode { get; set; }
        public string _3rdOffer_6thFeeAmount { get; set; }
        public string _3rdOffer_6thFeeDescription { get; set; }
        public string _3rdOffer_7thFeeCode { get; set; }
        public string _3rdOffer_7thFeeAmount { get; set; }
        public string _3rdOffer_7thFeeDescription { get; set; }
        public string _3rdOffer_8thFeeCode { get; set; }
        public string _3rdOffer_8thFeeAmount { get; set; }
        public string _3rdOffer_8thFeeDescription { get; set; }
        public string _3rdOffer_9thFeeCode { get; set; }
        public string _3rdOffer_9thFeeAmount { get; set; }
        public string _3rdOffer_9thFeeDescription { get; set; }
        public string _3rdOffer_10thFeeCode { get; set; }
        public string _3rdOffer_10thFeeAmount { get; set; }
        public string _3rdOffer_10thFeeDescription { get; set; }
        public string _3rdOffer_11thFeeCode { get; set; }
        public string _3rdOffer_11thFeeAmount { get; set; }
        public string _3rdOffer_11thFeeDescription { get; set; }
        public string _3rdOffer_12thFeeCode { get; set; }
        public string _3rdOffer_12thFeeAmount { get; set; }
        public string _3rdOffer_12thFeeDescription { get; set; }
        public string LoanSifterLink { get; set; }
        public string MiddleInitial { get; set; }
        public string RevolvingDebt { get; set; }
        public string MailDate { get; set; }
        public string NameSuffix { get; set; }
        public string FileType { get; set; }
        public string _720PlusCreditScore { get; set; }
        public string AA_SalesAssociate { get; set; }
        public string MortgageGoal { get; set; }
        public string CallCenterRepDIDforDialer { get; set; }
        public string Last4digitsofMailerPhone { get; set; }
        public string MailDropCount { get; set; }
        public string WeekNumber { get; set; }
        public string JobID { get; set; }
        public string SSNLast4Digits { get; set; }
        public string MortgageOpenDate { get; set; }
        public string CurrentLenderName { get; set; }
        public string LoanToValue { get; set; }
        public string ExistingHomeValue_Unused { get; set; }
        public string County_ { get; set; }
        public string AverageHomePrice { get; set; }
        public string TimeFrametoBuy { get; set; }
        public string RegistrationDate { get; set; }
        public string LoginDate { get; set; }
        public string PropertyViewCount { get; set; }
        public string EnrolledNewBeginningsDate { get; set; }
        public string DOB { get; set; }
        public string AAADialedOutLeads { get; set; }
        public string GrossMonthlyIncome { get; set; }
        public string CSSROutboundTimeStamp { get; set; }
        public string AAA_PersonalMortgageAdvisor { get; set; }
        public string LateOnMortgage { get; set; }
        public string HouseholdEmployment { get; set; }
        public string HouseholdEmploymentType { get; set; }
        public string VeteranStatus { get; set; }
        public string CurrentlyWorkingWithOtherLender { get; set; }
        public string OtherLenderName { get; set; }
        public string CustomerCreditOpinion { get; set; }
        public string CSSRRep { get; set; }
        public string LOOutbound { get; set; }
        public string UploadDate { get; set; }
        public string PreviousFundsSentDate { get; set; }
        public string PreviousBanker { get; set; }
        public string LoanProgram { get; set; }
        public string CLTV { get; set; }
        public string OutboundSaveRep { get; set; }
        public string AAAFileReceivedTimeStamp { get; set; }
        public string PreviousCampaign { get; set; }
        public string PreviousEncompassLoanNumber { get; set; }
        public string PreviousGFEApplicationDate { get; set; }
        public string PreviousInitialPACDate { get; set; }
        public string AAATransferTimeStamp { get; set; }
        public string CCROutboundSAVETimeStamp { get; set; }
        public string CCRInboundTimeStamp { get; set; }
        public string JR_LOOutboundTimeStamp { get; set; }
        public string AAALivetoLOTimeStamp { get; set; }
        public string ConventionalMortgageBalance { get; set; }
        public string FHAMortgageBalance { get; set; }
        public string VAMortgageBalance { get; set; }
        public string FannieTag { get; set; }
        public string FreddieTag { get; set; }
        public string BorrowerAge { get; set; }
        public string MortgageGoals { get; set; }
        public string VelocifyLeadIDNumber { get; set; }
        public string PrivacyConsent { get; set; }
        public string OwnorRent { get; set; }
        public string NBACCRTimeStamp { get; set; }
        public string NBAJRTIMESTAMP { get; set; }
        public string DistributedbyGetLead { get; set; }
        public string A_CustomerServiceRep { get; set; }
        public string MailerOverflowTimeStamp { get; set; }
        public string LiveTransferOverflowTimeStamp { get; set; }
        public string CustomerRelationsInboundTimeStamp { get; set; }
        public string NBAAppointment { get; set; }
        public string AdditionalBorrowerCash { get; set; }
        public string LowBalanceReviewTimeStamp { get; set; }
        public string SenttoFive9 { get; set; }
        public string UpdateModificationDate { get; set; }
        public string EncompassGUID { get; set; }
        public string EncompassExportResult { get; set; }
        public string EncompassFailureMessage { get; set; }
        public string AAACreditPull { get; set; }
        public string JRCreditPullTimeStamp { get; set; }
        public string PaymentCurrent { get; set; }
        public string Morethanone30daylateinlast12months { get; set; }
        public string Cashout { get; set; }
        public string CurrentMonthlyMIP { get; set; }
        public string TotalCurrentMonthlyMTGPayment { get; set; }
        public string CurrentMonthlyMTGPayment { get; set; }
        public string NewMonthlyMTGPayment { get; set; }
        public string NewMonthlyMIP { get; set; }
        public string TotalNewMonthlyMTGPayment { get; set; }
        public string TotalMonthlySavings { get; set; }
        public string TotalYearlySavings { get; set; }
        public string ReduceTerm { get; set; }
        public string GoodThruDate_DayPhone { get; set; }
        public string GoodThruDate_EveningPhone { get; set; }
        public string GoodThruDate_MobilePhone { get; set; }
        public string GoodThruDate_CoborrowerDayPhone { get; set; }
        public string GoodThruDate_CoborrowerEveningPhone { get; set; }
        public string GoodThruDate_CoborrowerMobilePhone { get; set; }
        public string ConfirmedCustomerEmailAddress { get; set; }
        public string AAALeadResult { get; set; }
        public string PreviousBranch { get; set; }
        public string LiveLeadAssignedTo { get; set; }
        public string WebFormSubmissionDate { get; set; }
        public string EloquaID { get; set; }
        public string ScheduledCallTime { get; set; }
        public string SMSPhone { get; set; }
        public string SMSOpt_Out { get; set; }
        public string SMSConsent { get; set; }
        public string PreviousFileStartedMilestoneDate { get; set; }
        public string PreviousRegistrationInvestorName { get; set; }
        public string PreviousInvestorName { get; set; }
        public string TollFreeNumber { get; set; }
        public string PreviousVelocifyLeadID { get; set; }
        public string AFileReceivedTimeStamp { get; set; }
        public string ACreditPull { get; set; }
        public string CurrentlyinVAloan { get; set; }
        public string LBR { get; set; }
        public string ReferringURL { get; set; }
        public string WRRSLeadCode { get; set; }
        public string ATransferTimeStamp { get; set; }
        public string TeamName { get; set; }
        public string SalesOverflowEmployee { get; set; }
        public string SalesOverflowLivetoLOTimeStamp { get; set; }
        public string SalesOverflowCallDirection { get; set; }
        public string PreviousServicingCORefNumber { get; set; }
        public string PreviousBorrEth { get; set; }
        public string Sub_ID { get; set; }
        public string ForeclosureorBankruptcy { get; set; }
        public string DischargeofForeclosureorBankruptcy { get; set; }
        public string Judgements { get; set; }
        public string MarketingZip { get; set; }
        public string CampaignMedium { get; set; }
        public string CampaignTerm { get; set; }
        public string CampaignContent { get; set; }
        public string CampaignName { get; set; }
        public string CampaignSource { get; set; }
        public string EncompassA_CLEvaluation_DoesnotQualifyReason { get; set; }
        public string UsableEquity { get; set; }
        public string A_CLEvaluationNotes { get; set; }
        public string MortgageBalanceData { get; set; }
        public string LoanAmountData { get; set; }
        public string MortgageBalance_1stData { get; set; }
        public string BranchLoanCoordinator { get; set; }
        public string DistributionPath { get; set; }
        public string PreviousVelocifyStatus { get; set; }
        public string PreviousVelocifyDateAdded { get; set; }
        public string AppraisedValue { get; set; }
        public string TopRatio { get; set; }
        public string BottomRatio { get; set; }
        public string InsuranceMtgInsPeriodicFactor { get; set; }
        public string ExpensesProposedMtgIns { get; set; }
        public string CashFromBorr { get; set; }
        public string TILIntlDisclosureProvidedDate { get; set; }
        public string MilestoneDate_Submittal { get; set; }
        public string FundedMilestoneDate { get; set; }
        public string DateServicingRightswereTransferred { get; set; }
        public string DistributionBranch { get; set; }
        public string DistributionLoanType { get; set; }
        public string E_FileCreditPullDate { get; set; }
        public string E_FileApplicationDate { get; set; }
        public string E_FileLACDate_Rename { get; set; }
        public string E_FilePacDate { get; set; }
        public string EncompassRecycleEligible { get; set; }
        public string EncompassRate { get; set; }
        public string EncompassLoanInfoRefiPurpose { get; set; }
        public string EncompassLoanPurpose { get; set; }
        public string EncompassLoanTerm { get; set; }
        public string EncompassClosingRequestForm_BranchName { get; set; }
        public string EncompassCo_BorrEmail { get; set; }
        public string EncompassDateServicingRightswereTransferred { get; set; }
        public string EncompassServicingLoansResold { get; set; }
        public string EncompassLoanOfficer { get; set; }
        public string EncompassPayoffAlertReceivedDate { get; set; }
        public string EncompassVALoanSummCreditScore { get; set; }
        public string EncompassPayoffComments { get; set; }
        public string EncompassServicingRightsRetained { get; set; }
        public string EncompassRetainedNewLoanNumber { get; set; }
        public string EncompassServicingRightsComments { get; set; }
        public string EncompassPayoffRequestOrigination { get; set; }
        public string EncompassMilestoneDate_Application { get; set; }
        public string EncompassMilestoneDate_Approval { get; set; }
        public string EncompassMilestoneDate_ClearToClose { get; set; }
        public string EncompassMilestoneDate_CondApproval { get; set; }
        public string EncompassMilestoneDate_DocPreparation { get; set; }
        public string EncompassMilestoneDate_DocsSigning { get; set; }
        public string EncompassMilestoneDate_Funding { get; set; }
        public string EncompassMilestoneDate_ProcessOpen { get; set; }
        public string EncompassMilestoneDate_Processing { get; set; }
        public string EncompassMilestoneDate_Purchased { get; set; }
        public string EncompassMilestoneDate_Qualification { get; set; }
        public string EncompassMilestoneDate_Resubmittal { get; set; }
        public string EncompassMilestoneDate_Shipping { get; set; }
        public string EncompassMilestoneDate_Started { get; set; }
        public string EncompassMilestoneDate_Submittal { get; set; }
        public string EncompassMilestoneDate_Reconciled { get; set; }
        public string EncompassMilestoneDate_Completion { get; set; }
        public string EncompassLoanStatus { get; set; }
        public string EncompassCurrentStatusDate { get; set; }
        public string EncompassA_CLEvaluation_DoesnotQualify { get; set; }
        public string EncompassCreditReceivedDate { get; set; }
        public string EncompassGFEApplicationDate { get; set; }
        public string EncompassTILIntlDisclosureProvidedDate { get; set; }
        public string EncompassInitialPACDate { get; set; }
        public string EncompassLoanFolderName { get; set; }
        public string EncompassCommitmentNumber { get; set; }
        public string EncompassPurchaseAdviceDate { get; set; }
        public string EncompassInvestorName { get; set; }
        public string MarketingTypeExec { get; set; }
        public string BusinessChannel { get; set; }
        public string CampaignType { get; set; }
        public string Vendor { get; set; }
        public string VendorAMBNumber { get; set; }
        public string DataSource { get; set; }
        public string OrderingBranchEncompassCode { get; set; }
        public string VendorProduct { get; set; }
        public string VendorSubProduct { get; set; }
        public string EncompassLoanAmountData { get; set; }
        public string EncompassFundsSentDate { get; set; }
        public string EncompassLoanNumber { get; set; }
        public string EncompassTestField { get; set; }
        public string LastDispositionIntake { get; set; }
        public string LastDispositionDateIntake { get; set; }
        public string LastDispositionPre_Qualified { get; set; }
        public string LastDispositionDatePre_Qualified { get; set; }
        public string LastDispositionShopping { get; set; }
        public string LastDispositionDateShopping { get; set; }
        public string LastDispositionNotInterestedLF { get; set; }
        public string LastDispositionDateNotInterestedLF { get; set; }
        public string LastDispositionIncomeDocsReceived { get; set; }
        public string LastDispositionDateIncomeDocsReceived { get; set; }
        public string LastDispositionContactAttempt_LF { get; set; }
        public string LastDispositionDateContactAttempt_LF { get; set; }
        public string LastDispositionFollowUpLF { get; set; }
        public string LastDispositionDateFollowUpLF { get; set; }
        public string AgentRelationshipLevel { get; set; }
        public string LastDispositionIntakeFollowUp { get; set; }
        public string LastDispositionDateIntakeFollowUp { get; set; }
        public string EmailData { get; set; }
        public string PreviousEncompassFolder { get; set; }
        public string PreviousEncompassLOAssistant { get; set; }
        public string PreviousEncompassLoanSource { get; set; }
        public string PreviousEncompassMilestone { get; set; }
        public string Experian { get; set; }
        public string TransUnion { get; set; }
        public string Equifax { get; set; }
        public string RevolvingDebt_UCS { get; set; }
        public string EndorsementMonth { get; set; }
        public string CustomerProfile { get; set; }
        public string CreditReportNumber { get; set; }
        public string CreditReportLink { get; set; }
        public string AdditionalCashPurpose { get; set; }
        public string Debtover10k { get; set; }
        public string SSN_UCS { get; set; }
        public string DateBankruptcyFiled { get; set; }
        public string DateForeclosureFiled { get; set; }
        public string UCSResponse { get; set; }
        public string GrossAnnualIncome { get; set; }
        public string BranchTollFreeNumber { get; set; }
        public string TollFreeNumberK8 { get; set; }
        public string MailerBranch { get; set; }
        public string MailerMortgageOpenDate { get; set; }
        public string BranchManager { get; set; }
        public string BranchManager2 { get; set; }
        public string BranchManager3 { get; set; }
        public string NeedRealEstateAgent { get; set; }
        public string SelfEmployed { get; set; }
        public string RealEstateAgent { get; set; }
        public string VendorLeadLink { get; set; }
        public string LoanTransferredDate { get; set; }
        public string ProspectorPastClient { get; set; }
        public string BlendID { get; set; }
        public string BranchManagerBranchName { get; set; }
        public string OpenMortgageMonthlyPayment { get; set; }
        public string ExternalID { get; set; }
        public string OtherUserID { get; set; }
        public string Triggerversion { get; set; }
    }
}
